window.routes = {
  endpoints: {
    workflows: 'workflows',
    pipelines: 'pipelines',
    step_bundles: 'step_bundles',
    secrets: 'secrets',
    env_vars: 'env_vars',
    triggers: 'triggers',
    stack: 'stack',
    licenses: 'licenses',
    yml: 'yml',
  },
  templates: {
    workflows: 'templates/workflows.html',
    pipelines: 'templates/pipelines.html',
    step_bundles: 'templates/step_bundles.html',
    secrets: 'templates/secrets.html',
    env_vars: 'templates/env_vars.html',
    triggers: 'templates/triggers.html',
    stack: 'templates/stack.html',
    licenses: 'templates/licenses.html',
    yml: 'templates/yml.html',
    workflows_workflow_description: 'templates/workflows-workflow_description.html',
    add_step_sidebar: 'templates/add_step_sidebar.html',
    add_step_sidebar_step: 'templates/add_step_sidebar_step.html',
  },
  website: {
    dashboard_path: '/dashboard',
    workspace_secrets_path: '/workspaces/<workspace_slug>/settings/shared-resources',
    workspace_plan_selector_path: '/organization/<workspace_slug>/credit_subscription/plan_selector_page',
    app_path: '/app/<app_slug>',
    app_path_get: '/app/<app_slug>.json',
    app_start_build_path: '/app/<app_slug>/build/start.json',
    app_data_get: '/api/app/<app_slug>.json',
    app_update: '/api/app/<app_slug>.json',
    app_config_post: '/api/app/<app_slug>/config.json',
    app_config_get: '/api/app/<app_slug>/config.json',
    app_codesigndoc_script_get: "/api/app/<app_slug>/codesigndoc.json'",
    product_tour_shown_get: '/api/app/<app_slug>/product_tour_shown',
    current_user_beta_tags_get: '/me/profile/beta_tags.json',
    current_user_metadata_get: '/me/profile/metadata.json?key=<metadata_key>',
    current_user_metadata_put: '/me/profile/metadata.json',
    get_org_plan_data: '/organization/<org_slug>/payment_subscription_status',
    yml_post: '/api/app/<app_slug>/config.json',
    yml_get: '/api/app/<app_slug>/config.yml',
    secrets_post: '/api/app/<app_slug>/secrets-without-values',
    secrets_get: '/api/app/<app_slug>/secrets-without-values',
    pipeline_config_get: '/app/<app_slug>/pipeline_config',
    secret_value_get: '/api/app/<app_slug>/secrets/<secret_key>.json',
    bitrise_steplib_get: 'https://bitrise-steplib-collection.s3.amazonaws.com/spec.json.gz',
    default_outputs_get: '/api/app/<app_slug>/default_step_outputs.json',
    machine_type_configs_get: '/app/<app_slug>/machine_type_configs',
    stack_get: '/app/<app_slug>/stack',
    stacks_get: '/app/<app_slug>/all_stack_info',
    prov_profile_create: '/api/app/<app_slug>/prov_profile_document/create.json',
    prov_profile_get_details: '/prov_profile_document/details/<prov_profile_id>.json',
    prov_profiles_get: '/api/app/<app_slug>/prov_profile_document/show.json',
    prov_profile_download: '/prov_profile_document/<prov_profile_id>',
    prov_profile_finalize_upload: '/prov_profile_document/<prov_profile_id>/upload_ended.json',
    prov_profile_is_expose_state_update: '/prov_profile_document/<prov_profile_id>/update_is_expose.json',
    prov_profile_protect: '/prov_profile_document/<prov_profile_id>/protect.json',
    prov_profile_delete: '/api/app/<app_slug>/prov_profile_document/<prov_profile_id>/delete.json',
    prov_profiles_delete_all: '/api/app/<app_slug>/prov_profile_document/delete.json',
    certificate_create: '/api/app/<app_slug>/build_certificate/create.json',
    certificate_finalize_upload: '/build_certificate/<certificate_id>/upload_ended.json',
    certificates_get: '/api/app/<app_slug>/build_certificate/show.json',
    certificate_download: '/build_certificate/<certificate_id>',
    certificate_get_details: '/build_certificate/details/<certificate_id>.json',
    certificate_is_expose_state_update: '/build_certificate/<certificate_id>/update_is_expose.json',
    certificate_password_save: '/build_certificate/<certificate_id>/password.json',
    certificate_protect: '/build_certificate/<certificate_id>/protect.json',
    certificate_delete: '/api/app/<app_slug>/build_certificate/<certificate_id>/delete.json',
    certificates_delete_all: '/api/app/<app_slug>/build_certificate/delete.json',
    generic_file_create: '/api/app/<app_slug>/project_file_storage_document/create.json',
    generic_file_finalize_upload: '/project_file_storage_document/<generic_file_id>/upload_ended.json',
    generic_files_get: '/api/app/<app_slug>/project_file_storage_document/show.json',
    generic_file_is_expose_state_update: '/project_file_storage_document/<generic_file_id>/update_is_expose.json',
    generic_file_download: '/project_file_storage_document/<generic_file_id>',
    generic_file_protect: '/project_file_storage_document/<generic_file_id>/protect.json',
    generic_file_delete: '/api/app/<app_slug>/project_file_storage_document/<generic_file_id>/delete.json',
    keystore_file_metadata_save: '/project_file_storage_document/<keystore_file_id>/exposed_meta.json',
    team_test_devices: '/api/app/<app_slug>/team-test-devices.json',
    apple_developer_account_get: '/me/profile/apple_developer_account.json',
    apple_developer_account_connect: '/me/profile/apple_developer_account.json',
    apple_developer_account_connection_delete: '/me/profile/apple_developer_account.json',
    apple_developer_account_two_step_auth_select_device_post:
      '/me/profile/apple_developer_account/two_step_auth_select_device.json',
    apple_developer_account_two_step_auth_verify_code_post:
      '/me/profile/apple_developer_account/two_step_auth_verify_code.json',
    apple_developer_account_two_factor_auth_verify_code_post:
      '/me/profile/apple_developer_account/two_factor_auth_verify_code.json',
    apple_developer_account_default_team_post: '/me/profile/apple_developer_account/default_team.json',
    workflows_and_pipelines: '/app/<app_slug>/workflows-and-pipelines',
    get_org_beta_tags: '/organization/<org_slug>/beta_tags',
  },
  local_server: {
    cancel_api_connection_close: '/api/connection',
    close_api_connection: '/api/connection',
    app_config_post: '/api/bitrise-yml.json',
    app_config_get: '/api/bitrise-yml.json',
    yml_post: '/api/bitrise-yml',
    yml_get: '/api/bitrise-yml',
    secrets_post: '/api/secrets',
    secrets_get: '/api/secrets',
    libraries_fetch: '/api/spec',
    step_config_fetch: '/api/step-info',
    default_outputs_get: '/api/default-outputs',
  },
  devcenter: {
    bitrise_cli: 'https://devcenter.bitrise.io/en/bitrise-cli.html',
    env_var_is_expand:
      'https://devcenter.bitrise.io/getting-started/getting-started-steps/#environment-variables-as-step-inputs',
    m1_stacks: 'https://devcenter.bitrise.io/en/infrastructure/build-stacks/apple-silicon-m1-stacks',
  },
  blog: {
    new_triggers: 'http://blog.bitrise.io/2016/09/23/do-more-with-triggers.html',
  },
  other: {
    bitrise_available_stacks: 'http://devcenter.bitrise.io/infrastructure/available-stacks',
    bitrise_workflow_editor_source_code: 'https://github.com/bitrise-io/bitrise-workflow-editor',
    github_step_yml_path: 'https://raw.githubusercontent.com/<step_path>/<step_version>/step.yml',
  },
};
