package config

const (
	// DefaultPort ...
	DefaultPort = "3645"
	// DefaultFrontendHost ...
	DefaultFrontendHost = "localhost"
	// DefaultFrontendPort ...
	DefaultFrontendPort = "4567"

	// MinimalValidSecrets ...
	MinimalValidSecrets = "{}"
	// MinimalValidBitriseYML ...
	MinimalValidBitriseYML = "format_version: 1.3.0"
)

var (
	// BitriseYMLPath ...
	BitriseYMLPath string
	// SecretsYMLPath ...
	SecretsYMLPath string
)
