format_version: "11"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios
services:
  postgres:
    image: postgres:13
containers:
  ruby:
    image: ruby:3.2
app:
  envs:
  - ACCESS_KEY: "120"
  - GITHUB_TOKEN: GITHUB_TOKEN_195
    opts:
      is_expand: true
  - SLACK_WEBHOOK: https://tempuri.org-g
workflows:
  wf1: {}
