---
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other
pipelines:
  dag-fan-out-fan-in:
    workflows:
      Pipeline-generator: {}
      A:
        run_if:
          expression: "{{ false }}"
        depends_on:
        - Pipeline-generator
      B:
        depends_on:
        - A
      C:
        run_if:
          expression: "{{ false }}"
        depends_on:
        - A
      D:
        depends_on:
        - B
        - C
      E:
        depends_on:
        - D
      F:
        depends_on:
        - D
      G:
        depends_on:
        - E
        - F
      H:
        depends_on:
        - A
      I:
        depends_on:
        - H
      J:
        depends_on:
        - I
      K:
        depends_on:
        - J
  dag-pipeline:
    workflows:
      primary_12: {}
      primary_11:
        depends_on:
        - primary_12
      primary_10:
        depends_on:
        - primary_12
      primary_9:
        depends_on:
        - primary_12
      primary_8:
        depends_on:
        - primary_12
      primary_7:
        depends_on:
        - primary_11
        - primary_10
        - primary_9
        - primary_8
      primary: {}
      primary_1: {}
      primary_2:
        depends_on:
        - primary
        - primary_1
      primary_3:
        depends_on:
        - primary_2
      primary_4:
        depends_on:
        - primary_2
      primary_5:
        depends_on:
        - primary_3
        - primary_1
  dag-single-pipeline:
    workflows:
      primary: {}
  dag-train-pipeline:
    workflows:
      primary: {}
      primary_1:
        depends_on:
        - primary
      primary_2:
        depends_on:
        - primary_1
      primary_3:
        depends_on:
        - primary_2
workflows:
  _util:
    steps:
    - script@1:
        inputs:
        - script_file_path:
        - content: "#!/bin/bash\nMAXWAIT=30\necho \"Waiting\"\nsleep $((RANDOM % MAXWAIT))
            \     \necho \"Done waiting!\""
        run_if: 'false'
  A:
    before_run:
    - _util
  B:
    before_run:
    - _util
  C:
    before_run:
    - _util
    steps:
    - script@1:
        inputs:
        - script_file_path:
        - content: exit 1
  D:
    before_run:
    - _util
  E:
    before_run:
    - _util
  F:
    before_run:
    - _util
  G:
    before_run:
    - _util
  H:
    before_run:
    - _util
  I:
    before_run:
    - _util
  J:
    before_run:
    - _util
  K:
    before_run:
    - _util
  Pipeline-generator:
    before_run:
    - _util
  primary:
    before_run:
    - _util
  primary_1:
    before_run:
    - _util
  primary_10:
    before_run:
    - _util
  primary_11:
    before_run:
    - _util
  primary_12:
    before_run:
    - _util
  primary_2:
    before_run:
    - _util
  primary_3:
    before_run:
    - _util
  primary_4:
    before_run:
    - _util
  primary_5:
    before_run:
    - _util
  primary_6:
    before_run:
    - _util
  primary_7:
    before_run:
    - _util
  primary_8:
    before_run:
    - _util
  primary_9:
    before_run:
    - _util
meta:
  bitrise.io:
    stack: osx-xcode-edge
    machine_type_id: g2-m1.4core
trigger_map:
- push_branch: main
  type: push
  workflow: primary
- pull_request_source_branch: "*"
  type: pull_request
  pipeline: dag-fan-out-fan-in
